openapi: 3.0.0
info:
  title: 'Desarrollo Software Web - Unidad 1 - API en desarrollo, no funcional'
  version: '1.0'
servers:
  - url: http://localhost
paths:
  /proyectos/:
    get:
      summary: 'Obtener proyectos'
      description: Listar todos los proyectos
      responses:
        '200':
          description: Resultado exitoso, devuelve JSON con todos los proyectos
          content:
            application/json: {}
        '401':
          description: No tiene autorizaci贸n
      security:
        - BearerGet: []

    post:
      summary: 'Agregar Proyecto'
      description: Agrega un proyecto de la empresa a la base de datos, formato JSON
      responses:
        '200':
          description: Resultado exitoso, nuevo servicio queda guardado en la base de datos
        '401':
          description: No tiene autorizaci贸n para el endpoint
      security:
        -
          BearerPost: []

    patch:
      summary: 'Actualizar Proyecto'
      description: Agrega un proyecto de la empresa a la base de datos, formato JSON
      responses:
        '200':
          description: Resultado exitoso, nuevo servicio queda guardado en la base de datos
        '401':
          description: No tiene autorizaci贸n para el endpoint
      security:
        -
          BearerPost: []

    delete:
      summary: Eliminar un proyecto
      description: Elimina un proyecto de la base de datos
      parameters:
        -
          name: id
          in: query
          description: ID del objeto
          required: false
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Eliminaci贸n ok
          content:
            application/json: {}
        401:
            description: "Error: no autorizado"
      security:
          -
              BearerDelete: []
